/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author HP
 */
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import javax.swing.JFileChooser;
import Model.PhotoStorage;

public class DashboardFrame extends javax.swing.JFrame {

    CardLayout cl;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
        this.setTitle("myMemo");
        cl = (CardLayout) WorkingPanel.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        variablePanel = new javax.swing.JPanel();
        PhotosButton = new javax.swing.JButton();
        VideoButton = new javax.swing.JButton();
        AlbumButton = new javax.swing.JButton();
        DocumentsButton = new javax.swing.JButton();
        ScreenshotssButton = new javax.swing.JButton();
        FavouritesButton = new javax.swing.JButton();
        BinButton = new javax.swing.JButton();
        Collections = new javax.swing.JLabel();
        Storage = new javax.swing.JLabel();
        WorkingPanel = new javax.swing.JPanel();
        clPhotos = new javax.swing.JPanel();
        clAlbums = new javax.swing.JPanel();
        clDocuments = new javax.swing.JPanel();
        clScreenshots = new javax.swing.JPanel();
        clFavourites = new javax.swing.JPanel();
        clBin = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clVideos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ActualLayoutPanel = new javax.swing.JPanel();
        SearchingPanel = new javax.swing.JPanel();
        SearchTextField = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        NotificationButton = new javax.swing.JButton();
        ProfileButton = new javax.swing.JButton();
        PlusButton = new javax.swing.JButton();
        SortComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        SelectButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        variablePanel.setBackground(new java.awt.Color(232, 164, 140));
        variablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PhotosButton.setBackground(new java.awt.Color(243, 199, 181));
        PhotosButton.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        PhotosButton.setForeground(new java.awt.Color(255, 255, 255));
        PhotosButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\camera.png")); // NOI18N
        PhotosButton.setText("Photos");
        PhotosButton.setBorder(null);
        PhotosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhotosButtonActionPerformed(evt);
            }
        });
        variablePanel.add(PhotosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 240, 50));

        VideoButton.setBackground(new java.awt.Color(243, 199, 181));
        VideoButton.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        VideoButton.setForeground(new java.awt.Color(255, 255, 255));
        VideoButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\video-camera.png")); // NOI18N
        VideoButton.setText("Videos");
        VideoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VideoButtonActionPerformed(evt);
            }
        });
        variablePanel.add(VideoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 240, 50));

        AlbumButton.setBackground(new java.awt.Color(243, 199, 181));
        AlbumButton.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        AlbumButton.setForeground(new java.awt.Color(255, 255, 255));
        AlbumButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\album.png")); // NOI18N
        AlbumButton.setText("Albums");
        AlbumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlbumButtonActionPerformed(evt);
            }
        });
        variablePanel.add(AlbumButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 240, 50));

        DocumentsButton.setBackground(new java.awt.Color(243, 199, 181));
        DocumentsButton.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        DocumentsButton.setForeground(new java.awt.Color(255, 255, 255));
        DocumentsButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\google-docs.png")); // NOI18N
        DocumentsButton.setText("Documents");
        DocumentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentsButtonActionPerformed(evt);
            }
        });
        variablePanel.add(DocumentsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 240, 50));

        ScreenshotssButton.setBackground(new java.awt.Color(243, 199, 181));
        ScreenshotssButton.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        ScreenshotssButton.setForeground(new java.awt.Color(255, 255, 255));
        ScreenshotssButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\Screenshot.png")); // NOI18N
        ScreenshotssButton.setText("Screenshots");
        ScreenshotssButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScreenshotssButtonActionPerformed(evt);
            }
        });
        variablePanel.add(ScreenshotssButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 240, 50));

        FavouritesButton.setBackground(new java.awt.Color(243, 199, 181));
        FavouritesButton.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        FavouritesButton.setForeground(new java.awt.Color(255, 255, 255));
        FavouritesButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\star.png")); // NOI18N
        FavouritesButton.setText("Favourites");
        FavouritesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavouritesButtonActionPerformed(evt);
            }
        });
        variablePanel.add(FavouritesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 240, 50));

        BinButton.setBackground(new java.awt.Color(243, 199, 181));
        BinButton.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        BinButton.setForeground(new java.awt.Color(255, 255, 255));
        BinButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\bin.png")); // NOI18N
        BinButton.setText("Bin");
        BinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinButtonActionPerformed(evt);
            }
        });
        variablePanel.add(BinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 240, 50));

        Collections.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        Collections.setText("Collections");
        variablePanel.add(Collections, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        Storage.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        Storage.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\cloud.png")); // NOI18N
        Storage.setText("Storage");
        variablePanel.add(Storage, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 610, 120, -1));

        getContentPane().add(variablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 320, 910));

        WorkingPanel.setBackground(new java.awt.Color(255, 255, 255));
        WorkingPanel.setLayout(new java.awt.CardLayout());

        clPhotos.setBackground(new java.awt.Color(255, 255, 255));
        clPhotos.setLayout(new java.awt.GridBagLayout());
        WorkingPanel.add(clPhotos, "card3");

        clAlbums.setBackground(new java.awt.Color(255, 0, 0));
        clAlbums.setLayout(new java.awt.GridLayout(1, 0));
        WorkingPanel.add(clAlbums, "card4");

        clDocuments.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout clDocumentsLayout = new javax.swing.GroupLayout(clDocuments);
        clDocuments.setLayout(clDocumentsLayout);
        clDocumentsLayout.setHorizontalGroup(
            clDocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        clDocumentsLayout.setVerticalGroup(
            clDocumentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        WorkingPanel.add(clDocuments, "card5");

        clScreenshots.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout clScreenshotsLayout = new javax.swing.GroupLayout(clScreenshots);
        clScreenshots.setLayout(clScreenshotsLayout);
        clScreenshotsLayout.setHorizontalGroup(
            clScreenshotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        clScreenshotsLayout.setVerticalGroup(
            clScreenshotsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        WorkingPanel.add(clScreenshots, "card6");

        clFavourites.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout clFavouritesLayout = new javax.swing.GroupLayout(clFavourites);
        clFavourites.setLayout(clFavouritesLayout);
        clFavouritesLayout.setHorizontalGroup(
            clFavouritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        clFavouritesLayout.setVerticalGroup(
            clFavouritesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        WorkingPanel.add(clFavourites, "card7");

        clBin.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout clBinLayout = new javax.swing.GroupLayout(clBin);
        clBin.setLayout(clBinLayout);
        clBinLayout.setHorizontalGroup(
            clBinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clBinLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
                .addContainerGap())
        );
        clBinLayout.setVerticalGroup(
            clBinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        WorkingPanel.add(clBin, "card9");

        clVideos.setBackground(new java.awt.Color(0, 102, 102));

        ActualLayoutPanel.setLayout(new java.awt.GridLayout(1, 0));
        jScrollPane2.setViewportView(ActualLayoutPanel);

        javax.swing.GroupLayout clVideosLayout = new javax.swing.GroupLayout(clVideos);
        clVideos.setLayout(clVideosLayout);
        clVideosLayout.setHorizontalGroup(
            clVideosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clVideosLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
                .addContainerGap())
        );
        clVideosLayout.setVerticalGroup(
            clVideosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clVideosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
        );

        WorkingPanel.add(clVideos, "card8");

        getContentPane().add(WorkingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 1210, 730));

        SearchingPanel.setBackground(new java.awt.Color(255, 255, 255));

        SearchTextField.setText("Search");
        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });

        SearchButton.setText("Search");

        NotificationButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\Notification.png")); // NOI18N
        NotificationButton.setBorder(null);
        NotificationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificationButtonActionPerformed(evt);
            }
        });

        ProfileButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\Profile.png")); // NOI18N
        ProfileButton.setBorder(null);

        PlusButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\Plus.png")); // NOI18N
        PlusButton.setBorder(null);
        PlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusButtonActionPerformed(evt);
            }
        });

        SortComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort by Name", "Sort by Date", "Sort by File TYpe" }));
        SortComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortComboBoxActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\favorite.png")); // NOI18N
        jButton1.setText("Add to Favourite");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SelectButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\check.png")); // NOI18N
        SelectButton.setText("Select");

        DeleteButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\bin.png")); // NOI18N
        DeleteButton.setText("Delete");

        jButton8.setText("Add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Magneto", 0, 10)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Pictures\\logo (2).jpg")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 0, 12)); // NOI18N
        jLabel2.setText("myMemo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SearchingPanelLayout = new javax.swing.GroupLayout(SearchingPanel);
        SearchingPanel.setLayout(SearchingPanelLayout);
        SearchingPanelLayout.setHorizontalGroup(
            SearchingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchingPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(SearchingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchingPanelLayout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SearchButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PlusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NotificationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(SearchingPanelLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(SortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(SelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        SearchingPanelLayout.setVerticalGroup(
            SearchingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchingPanelLayout.createSequentialGroup()
                .addGroup(SearchingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchingPanelLayout.createSequentialGroup()
                        .addGroup(SearchingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PlusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NotificationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(SearchingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(SearchingPanelLayout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addGroup(SearchingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SearchButton)
                                        .addComponent(jButton8)))
                                .addGroup(SearchingPanelLayout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addComponent(ProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(SearchingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(SelectButton)
                            .addComponent(DeleteButton)
                            .addComponent(SortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SearchingPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(SearchingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 120));

        setSize(new java.awt.Dimension(1539, 861));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FavouritesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavouritesButtonActionPerformed
        // TODO add your handling code here:
        WorkingPanel.add(clFavourites, "Favourites Panel");
        cl.show(WorkingPanel, "Favourites Panel");
    }//GEN-LAST:event_FavouritesButtonActionPerformed

    private void AlbumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlbumButtonActionPerformed
        // TODO add your handling code here:
        WorkingPanel.add(clAlbums, "Albums Panel");
        cl.show(WorkingPanel, "Albums Panel");
    }//GEN-LAST:event_AlbumButtonActionPerformed

    private void PhotosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhotosButtonActionPerformed
        // TODO add your handling code here:
        WorkingPanel.add(clPhotos, "Photos Panel");
        cl.show(WorkingPanel, "Photos Panel");
    }//GEN-LAST:event_PhotosButtonActionPerformed

    private void VideoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VideoButtonActionPerformed
        // TODO add your handling code here:
        WorkingPanel.add(clVideos, "Videos Panel");
        cl.show(WorkingPanel, "Videos Panel");
    }//GEN-LAST:event_VideoButtonActionPerformed

    private void DocumentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentsButtonActionPerformed
        // TODO add your handling code here:
        WorkingPanel.add(clDocuments, "Documents Panel");
        cl.show(WorkingPanel, "Documents Panel");
    }//GEN-LAST:event_DocumentsButtonActionPerformed

    private void ScreenshotssButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScreenshotssButtonActionPerformed
        // TODO add your handling code here:
        WorkingPanel.add(clScreenshots, "Screenshots Panel");
        cl.show(WorkingPanel, "Screenshots Panel");
    }//GEN-LAST:event_ScreenshotssButtonActionPerformed

    private void BinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinButtonActionPerformed
        // TODO add your handling code here:
        WorkingPanel.add(clBin, "Bin Panel");
        cl.show(WorkingPanel, "Bin Panel");
    }//GEN-LAST:event_BinButtonActionPerformed

    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextFieldActionPerformed

    private void NotificationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NotificationButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SortComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SortComboBoxActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed


    }//GEN-LAST:event_jButton8ActionPerformed

    private void PlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusButtonActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();

            // Add to storage
            storage.addPhoto(file.getName(), file.getAbsolutePath());
            int index = storage.getPhotos().size() - 1;

            // Create card and add to panel
            PhotoCard card = new PhotoCard(storage, index);
            clPhotos.add(card);
            clPhotos.revalidate();
            clPhotos.repaint();
        }


    }//GEN-LAST:event_PlusButtonActionPerformed

    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
     */
    private PhotoStorage storage = new PhotoStorage();

    public class PhotoCard extends JPanel {

        private JLabel titleLabel;
        private PhotoStorage storage;
        private int index;

        public PhotoCard(PhotoStorage storage, int index) {
            this.storage = storage;
            this.index = index;

            PhotoStorage.Photo p = storage.getPhotos().get(index);

            setPreferredSize(new Dimension(150, 150));
            setLayout(new BorderLayout());
            setBorder(BorderFactory.createLineBorder(Color.GRAY));

            // Photo
            JLabel photoLabel = new JLabel();
            Image img = new ImageIcon(p.getPath()).getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
            photoLabel.setIcon(new ImageIcon(img));
            photoLabel.setHorizontalAlignment(JLabel.CENTER);
            photoLabel.setVerticalAlignment(JLabel.CENTER);
            add(photoLabel, BorderLayout.CENTER);

            // Title
            titleLabel = new JLabel(p.getTitle(), SwingConstants.CENTER);
            add(titleLabel, BorderLayout.SOUTH);

            // Right-click menu
            JPopupMenu menu = new JPopupMenu();
            JMenuItem renameItem = new JMenuItem("Rename");
            JMenuItem deleteItem = new JMenuItem("Delete");

            renameItem.addActionListener(e -> renamePhoto());
            deleteItem.addActionListener(e -> deletePhoto());

            menu.add(renameItem);
            menu.add(deleteItem);
            this.setComponentPopupMenu(menu);

        }

        private void renamePhoto() {
            String newName = JOptionPane.showInputDialog(this, "Enter new name:", titleLabel.getText());
            if (newName != null && !newName.trim().isEmpty()) {
                titleLabel.setText(newName.trim());
                storage.renamePhoto(index, newName.trim());
            }
        }

        private void deletePhoto() {
            Container parent = getParent();
            if (parent != null) {
                parent.remove(this);
                parent.revalidate();
                parent.repaint();
                storage.removePhoto(index);
            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ActualLayoutPanel;
    private javax.swing.JButton AlbumButton;
    private javax.swing.JButton BinButton;
    private javax.swing.JLabel Collections;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DocumentsButton;
    private javax.swing.JButton FavouritesButton;
    private javax.swing.JButton NotificationButton;
    private javax.swing.JButton PhotosButton;
    private javax.swing.JButton PlusButton;
    private javax.swing.JButton ProfileButton;
    private javax.swing.JButton ScreenshotssButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JPanel SearchingPanel;
    private javax.swing.JButton SelectButton;
    private javax.swing.JComboBox<String> SortComboBox;
    private javax.swing.JLabel Storage;
    private javax.swing.JButton VideoButton;
    private javax.swing.JPanel WorkingPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JPanel clAlbums;
    private javax.swing.JPanel clBin;
    private javax.swing.JPanel clDocuments;
    private javax.swing.JPanel clFavourites;
    private javax.swing.JPanel clPhotos;
    private javax.swing.JPanel clScreenshots;
    private javax.swing.JPanel clVideos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel variablePanel;
    // End of variables declaration//GEN-END:variables
}
