/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 * DashboardFrame is the main application window for the myMemo photo management system.
 * It provides a comprehensive interface for organizing, viewing, and managing photos, screenshots,
 * and favorite items with support for undo/redo operations and file management.
 *
 * 
 * Key Features:
 * 
 *   Photo, screenshot, and favorites collection management
 *   Recycle bin functionality for deleted items
 *   Search and sort capabilities for media items
 *   Undo/Redo support using Ctrl+Z and Ctrl+Y
 *   Add items to favorites
 *   File browser integration for adding new media
 * 
 * 
 *
 * @author HP
 * @version 1.0
 * @see UndoRedoManager
 * @see PhotoStorage
 * @see MyQueue
 */
import java.awt.CardLayout;
import javax.swing.ImageIcon;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import javax.swing.JFileChooser;
import Model.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import Controller.*;

import java.awt.event.*;



public class DashboardFrame extends javax.swing.JFrame {
    /** Manager for undo and redo operations */
    private Controller.UndoRedoManager undoRedoManager = new Controller.UndoRedoManager();
    
    /** Queue for managing deleted items in the recycle bin */
    private MyQueue<Component> binQueue = new MyQueue<>();
    
    /** CardLayout for switching between different view panels */
    CardLayout cl;
    
    /** Logger for system events and debugging */
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());
    
    /** Storage manager for photo items */
    PhotoStorage PhotoStorage = new PhotoStorage();
    
    /**
     * Constructs the DashboardFrame and initializes all UI components.
     * Sets up keyboard shortcuts for undo (Ctrl+Z) and redo (Ctrl+Y) operations.
     * Initializes the main application window with title "myMemo".
     */
    public DashboardFrame() {
        initComponents();
        setupBinPopupMenu();
        // Undo (Ctrl+Z) / Redo (Ctrl+Y)
        InputMap im = this.getRootPane().getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = this.getRootPane().getActionMap();

        im.put(KeyStroke.getKeyStroke("control Z"), "undo");
        im.put(KeyStroke.getKeyStroke("control Y"), "redo");

        am.put("undo", new AbstractAction() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                undoRedoManager.undo();
                refreshPhotosPanel();
            }
        });
am.put("redo", new AbstractAction() {
    public void actionPerformed(java.awt.event.ActionEvent e) {
        undoRedoManager.redo();
        refreshPhotosPanel();
    }
});

        this.setTitle("myMemo");
        cl = (CardLayout) WorkingPanel.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        variablePanel = new javax.swing.JPanel();
        PhotosButton = new javax.swing.JButton();
        ScreenshotssButton = new javax.swing.JButton();
        FavouritesButton = new javax.swing.JButton();
        BinButton = new javax.swing.JButton();
        Collections = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        WorkingPanel = new javax.swing.JPanel();
        clPhotos = new javax.swing.JPanel();
        clScreenshots = new javax.swing.JPanel();
        clFavourites = new javax.swing.JPanel();
        clBin = new javax.swing.JPanel();
        SearchingPanel = new javax.swing.JPanel();
        SearchTextField = new javax.swing.JTextField();
        PlusButton = new javax.swing.JButton();
        SortComboBox = new javax.swing.JComboBox<>();
        AddToFavouritesButton = new javax.swing.JButton();
        AddItemsButton = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        variablePanel.setBackground(new java.awt.Color(232, 164, 140));
        variablePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PhotosButton.setBackground(new java.awt.Color(243, 199, 181));
        PhotosButton.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        PhotosButton.setForeground(new java.awt.Color(255, 255, 255));
        PhotosButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\camera.png")); // NOI18N
        PhotosButton.setText("Photos");
        PhotosButton.setBorder(null);
        PhotosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhotosButtonActionPerformed(evt);
            }
        });
        variablePanel.add(PhotosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 240, 50));

        ScreenshotssButton.setBackground(new java.awt.Color(243, 199, 181));
        ScreenshotssButton.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        ScreenshotssButton.setForeground(new java.awt.Color(255, 255, 255));
        ScreenshotssButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\Screenshot.png")); // NOI18N
        ScreenshotssButton.setText("Screenshots");
        ScreenshotssButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScreenshotssButtonActionPerformed(evt);
            }
        });
        variablePanel.add(ScreenshotssButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 240, 50));

        FavouritesButton.setBackground(new java.awt.Color(243, 199, 181));
        FavouritesButton.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        FavouritesButton.setForeground(new java.awt.Color(255, 255, 255));
        FavouritesButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\star.png")); // NOI18N
        FavouritesButton.setText("Favourites");
        FavouritesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FavouritesButtonActionPerformed(evt);
            }
        });
        variablePanel.add(FavouritesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 240, 50));

        BinButton.setBackground(new java.awt.Color(243, 199, 181));
        BinButton.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        BinButton.setForeground(new java.awt.Color(255, 255, 255));
        BinButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\bin.png")); // NOI18N
        BinButton.setText("Bin");
        BinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinButtonActionPerformed(evt);
            }
        });
        variablePanel.add(BinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 240, 50));

        Collections.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        Collections.setText("Collections");
        variablePanel.add(Collections, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 0, 24)); // NOI18N
        jLabel2.setText("myMemo");
        variablePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 130, -1));

        jLabel1.setFont(new java.awt.Font("Magneto", 0, 10)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Pictures\\logo (2).jpg")); // NOI18N
        variablePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 98));

        getContentPane().add(variablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 1030));

        WorkingPanel.setBackground(new java.awt.Color(255, 255, 255));
        WorkingPanel.setLayout(new java.awt.CardLayout());

        clPhotos.setBackground(new java.awt.Color(255, 255, 255));
        WorkingPanel.add(clPhotos, "card3");

        clScreenshots.setBackground(new java.awt.Color(255, 255, 255));
        WorkingPanel.add(clScreenshots, "card6");

        clFavourites.setBackground(new java.awt.Color(255, 255, 255));
        WorkingPanel.add(clFavourites, "card7");

        clBin.setBackground(new java.awt.Color(255, 255, 255));
        WorkingPanel.add(clBin, "card9");

        getContentPane().add(WorkingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 1210, 730));

        SearchingPanel.setBackground(new java.awt.Color(255, 255, 255));

        SearchTextField.setText("Search");
        SearchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextFieldActionPerformed(evt);
            }
        });

        PlusButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\Plus.png")); // NOI18N
        PlusButton.setBorder(null);
        PlusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusButtonActionPerformed(evt);
            }
        });

        SortComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort by Name" }));
        SortComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortComboBoxActionPerformed(evt);
            }
        });

        AddToFavouritesButton.setIcon(new javax.swing.ImageIcon("D:\\myMemo\\myMemo\\Image\\Icons\\favorite.png")); // NOI18N
        AddToFavouritesButton.setText("Add to Favourite");
        AddToFavouritesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddToFavouritesButtonActionPerformed(evt);
            }
        });

        AddItemsButton.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Add", "Add Photos", "Add Screenshot" }));
        AddItemsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemsButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Logout ->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchingPanelLayout = new javax.swing.GroupLayout(SearchingPanel);
        SearchingPanel.setLayout(SearchingPanelLayout);
        SearchingPanelLayout.setHorizontalGroup(
            SearchingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchingPanelLayout.createSequentialGroup()
                .addGroup(SearchingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchingPanelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(SortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(AddToFavouritesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(AddItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SearchingPanelLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 418, Short.MAX_VALUE)
                        .addComponent(PlusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addContainerGap())
        );
        SearchingPanelLayout.setVerticalGroup(
            SearchingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchingPanelLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(70, 70, 70))
            .addGroup(SearchingPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddToFavouritesButton))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchingPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(SearchingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SearchingPanelLayout.createSequentialGroup()
                        .addComponent(PlusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(SortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AddItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(SearchingPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1200, 120));

        setSize(new java.awt.Dimension(1539, 861));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Refreshes the photos panel by reloading all photo cards from PhotoStorage.
     * Clears existing components and repopulates with the current photo collection.
     */
    private void refreshPhotosPanel() {
    clPhotos.removeAll();

    for (int i = 0; i < PhotoStorage.getPhotos().size(); i++) {
        PhotoCard card = new PhotoCard(PhotoStorage, i);
        clPhotos.add(card);
    }

    clPhotos.revalidate();
    clPhotos.repaint();
}

    /**
     * Sets up the context menu (right-click popup) for the recycle bin panel.
     * Provides options for managing deleted items.
     */
    private void setupBinPopupMenu() {
        // Right-click menu for the bin panel
        JPopupMenu binMenu = new JPopupMenu();
        JMenuItem deleteAllItem = new JMenuItem("Delete All");

        deleteAllItem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                deleteAllFromBin();
            }
        });

        binMenu.add(deleteAllItem);
        clBin.setComponentPopupMenu(binMenu);
    }
    private void deleteAllFromBin() {
    while (!binQueue.isEmpty()) {
        Component card = binQueue.dequeue(); // remove from queue
        clBin.remove(card);                  // remove visually
    }

    clBin.revalidate();
    clBin.repaint();
}
    
    private void FavouritesButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // Display favorites panel
        WorkingPanel.add(clFavourites, "Favourites Panel");
        cl.show(WorkingPanel, "Favourites Panel");
    }                                                

    /**
     * Handles Photos button click to display photos panel.
     */
    private void PhotosButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // Display photos panel
        WorkingPanel.add(clPhotos, "Photos Panel");
        cl.show(WorkingPanel, "Photos Panel");
    }                                            

    /**
     * Handles Bin button click to display bin panel.
     */
    private void BinButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // Display bin panel
        WorkingPanel.add(clBin, "Bin Panel");
        cl.show(WorkingPanel, "Bin Panel");
    }                                         

    /**
     * Handles search text field submission.
     */
    private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // Execute search
        performSearch();
    }                                               

    /**
     * Refreshes the favorites panel by loading from the linked list.
     */
    // private void FavouritesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FavouritesButtonActionPerformed
    //     // TODO add your handling code here:
    //     WorkingPanel.add(clFavourites, "Favourites Panel");
    //     cl.show(WorkingPanel, "Favourites Panel");
    // }//GEN-LAST:event_FavouritesButtonActionPerformed

    // private void PhotosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhotosButtonActionPerformed
    //     // TODO add your handling code here:
    //     WorkingPanel.add(clPhotos, "Photos Panel");
    //     cl.show(WorkingPanel, "Photos Panel");
    // }//GEN-LAST:event_PhotosButtonActionPerformed

    // private void BinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinButtonActionPerformed
    //     // TODO add your handling code here:
    //     WorkingPanel.add(clBin, "Bin Panel");
    //     cl.show(WorkingPanel, "Bin Panel");
    // }//GEN-LAST:event_BinButtonActionPerformed

    // private void SearchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextFieldActionPerformed
    //     // TODO add your handling code here:
    //     performSearch();
    // }//GEN-LAST:event_SearchTextFieldActionPerformed

    // Clears and rebuilds clFavourites from the FavouriteItem linked list
private void refreshFavouritesPanel() {
    clFavourites.removeAll();

    FavouriteItem.traverse((item, idx) -> {
        FavoriteCard card = new FavoriteCard(item);
        clFavourites.add(card);
    });

    clFavourites.revalidate();
    clFavourites.repaint();
}

private int getSelectedPhotoIndex() {
    for (Component c : clPhotos.getComponents()) {
        if (c instanceof PhotoCard) {
            PhotoCard card = (PhotoCard) c;
            if (card.isSelected()) {
                return card.getIndex();
            }
        }
    }
    return -1;
}

    /**
     * Handles adding selected photo to favorites.
     */
    private void AddToFavouritesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddToFavouritesButtonActionPerformed
    int selectedIndex = getSelectedPhotoIndex(); // method to get selected photo index from clPhotos
    if (selectedIndex == -1) {
        JOptionPane.showMessageDialog(this, "No photo selected!");
        return;
    }

    // Get selected photo
    PhotoStorage.Photo selectedPhoto = PhotoStorage.getPhotos().get(selectedIndex);

    // Create FavouriteItem using the selected photo
    FavouriteItem fav = new FavouriteItem(
            selectedPhoto.getTitle(),
            selectedPhoto.getPath(),
            "photo"
    );

    // Add to linked list
    FavouriteItem.addFirst(fav);

    // Refresh favorites panel
    refreshFavouritesPanel();

    }//GEN-LAST:event_AddToFavouritesButtonActionPerformed

    private void SortComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortComboBoxActionPerformed
    String selected = (String) SortComboBox.getSelectedItem();

    if (selected == null) return;

    switch (selected) {
        case "Sort by Name":
            PhotoStorage.getPhotos().sort((p1, p2) -> p1.getTitle().compareToIgnoreCase(p2.getTitle()));
            break;

//        case "Sort by Date":
//            // If you have a date field in Photo, sort by it.
//            // For now, we can skip or sort by file creation time if implemented
//            break;
//
//        case "Sort by File TYpe":
//            PhotoStorage.getPhotos().sort((p1, p2) -> p1.getFileType().compareToIgnoreCase(p2.getFileType()));
//            break;
//
//        // Optional: add "Sort by Size"
//        case "Sort by Size":
//            PhotoStorage.getPhotos().sort((p1, p2) -> Integer.compare(p1.getSize(), p2.getSize()));
//            break;
    }

    // Refresh the photo panel to show sorted photos
    refreshPhotosPanel();
    }//GEN-LAST:event_SortComboBoxActionPerformed

    private void PlusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY); 
    
    // Allow only image files
    javax.swing.filechooser.FileNameExtensionFilter filter =
        new javax.swing.filechooser.FileNameExtensionFilter(
            "Image files", "png", "jpg", "jpeg", "gif"
        );
    chooser.setFileFilter(filter);

    int result = chooser.showOpenDialog(this); 
    if (result != JFileChooser.APPROVE_OPTION) return;

    File file = chooser.getSelectedFile();

    // Execute with undo/redo
    undoRedoManager.execute(new Controller.ActionCommand(
        () -> { // DO
            PhotoStorage.addPhoto(file.getName(), file.getAbsolutePath());
            refreshPhotosPanel();
        },
        () -> { // UNDO
            int lastIndex = PhotoStorage.getPhotos().size() - 1;
            if (lastIndex >= 0) {
                PhotoStorage.removePhoto(lastIndex);
                refreshPhotosPanel();
            }
        }
    ));
       
    }//GEN-LAST:event_PlusButtonActionPerformed
                                    

    private void AddItemsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemsButtonActionPerformed
    String selectedOption = (String) AddItemsButton.getSelectedItem(); 
    if (selectedOption.equals("Add")) return;

    JFileChooser chooser = new JFileChooser();
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

    // Set filter just for UI hint
    if (selectedOption.equals("Add Photos") || selectedOption.equals("Add Screenshot")) {
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                "Image files", "png", "jpg", "jpeg", "gif"));
    } 
    int result = chooser.showOpenDialog(this);
    if (result != JFileChooser.APPROVE_OPTION) return;

    File file = chooser.getSelectedFile();
    String name = file.getName();
    String ext = name.substring(name.lastIndexOf(".") + 1).toLowerCase();

    boolean valid = false;
    if (selectedOption.equals("Add Photos") || selectedOption.equals("Add Screenshot")) {
        valid = ext.equals("png") || ext.equals("jpg") || ext.equals("jpeg") || ext.equals("gif");
    } 
    if (!valid) {
        JOptionPane.showMessageDialog(this, 
            "Invalid file type! Please select a valid " + 
            (selectedOption.contains("Video") ? "video" : "image") + " file.");
        return; // Stop execution
    }

    // Now safe: Add only once via undoRedoManager
    final String filePath = file.getAbsolutePath();
    final String fileTitle = file.getName();

    undoRedoManager.execute(new Controller.ActionCommand(
        () -> { // DO
            PhotoStorage.addPhoto(fileTitle, filePath);
            int index = PhotoStorage.getPhotos().size() - 1;
            PhotoCard card = new PhotoCard(PhotoStorage, index);

            switch (selectedOption) {
                case "Add Photos":
                    clPhotos.add(card);
                    clPhotos.revalidate();
                    clPhotos.repaint();
                    break;
                case "Add Screenshot":
                    clScreenshots.add(card);
                    clScreenshots.revalidate();
                    clScreenshots.repaint();
                    break;
                case "Add Favourites":
                    clFavourites.add(card);
                    clFavourites.revalidate();
                    clFavourites.repaint();
                    break;
            }
        },
        () -> { // UNDO
            int lastIndex = PhotoStorage.getPhotos().size() - 1;
            if (lastIndex >= 0) {
                PhotoStorage.removePhoto(lastIndex);
                refreshPhotosPanel(); // Optional: or remove from specific panel
            }
        }
    ));
    }//GEN-LAST:event_AddItemsButtonActionPerformed

    private void performSearch() {
    String query = SearchTextField.getText().trim().toLowerCase();

    // If empty → show all photos
    if (query.isEmpty()) {
        refreshPhotosPanel();
        return;
    }

    // Clear current panel
    clPhotos.removeAll();

    // Loop through photos and show only those whose title contains the query
    for (int i = 0; i < PhotoStorage.getPhotos().size(); i++) {
        PhotoStorage.Photo p = PhotoStorage.getPhotos().get(i);
        if (p.getTitle().toLowerCase().contains(query)) {
            PhotoCard card = new PhotoCard(PhotoStorage, i);
            clPhotos.add(card);
        }
    }

    clPhotos.revalidate();
    clPhotos.repaint();
}

    
    private void ScreenshotssButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScreenshotssButtonActionPerformed
        // TODO add your handling code here:
        WorkingPanel.add(clScreenshots, "Screenshots Panel");
        cl.show(WorkingPanel, "Screenshots Panel");
    }//GEN-LAST:event_ScreenshotssButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            // Open SignIn frame
    SigninFrame signIn = new SigninFrame();
    signIn.setVisible(true);

    // Close current Dashboard frame
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public class FavoriteCard extends JPanel {

    private JLabel titleLabel;

    public FavoriteCard(FavouriteItem item) {
        setPreferredSize(new Dimension(150, 150));
        setLayout(new BorderLayout());
        setBorder(BorderFactory.createLineBorder(Color.GRAY));

        // Image
        JLabel photoLabel = new JLabel();
        ImageIcon icon = new ImageIcon(item.getPath());
        Image img = icon.getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
        photoLabel.setIcon(new ImageIcon(img));
        photoLabel.setHorizontalAlignment(JLabel.CENTER);
        photoLabel.setVerticalAlignment(JLabel.CENTER);
        add(photoLabel, BorderLayout.CENTER);

        // Title
        titleLabel = new JLabel(item.getTitle(), SwingConstants.CENTER);
        add(titleLabel, BorderLayout.SOUTH);

        // Right-click menu
        JPopupMenu menu = new JPopupMenu();
        JMenuItem deleteItem = new JMenuItem("Delete");
        deleteItem.addActionListener(e -> deleteCard());
        menu.add(deleteItem);
        setComponentPopupMenu(menu);
    }

    private void deleteCard() {
        Container parent = getParent();
        if (parent != null) {
            parent.remove(this);
            parent.revalidate();
            parent.repaint();
        }
    }
}

    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
     */


    public class PhotoCard extends JPanel {

        private JLabel titleLabel;
        private PhotoStorage PhotoStorage;
        private int index;
        private boolean selected = false;

        public PhotoCard(PhotoStorage PhotoStorage, int index) {
            this.PhotoStorage = PhotoStorage;
            this.index = index;

            PhotoStorage.Photo p = PhotoStorage.getPhotos().get(index);

            setPreferredSize(new Dimension(150, 150));
            setLayout(new BorderLayout());
            setBorder(BorderFactory.createLineBorder(Color.GRAY));

            // Photo
            JLabel photoLabel = new JLabel();
            Image img = new ImageIcon(p.getPath()).getImage().getScaledInstance(120, 120, Image.SCALE_SMOOTH);
            photoLabel.setIcon(new ImageIcon(img));
            photoLabel.setHorizontalAlignment(JLabel.CENTER);
            photoLabel.setVerticalAlignment(JLabel.CENTER);
            add(photoLabel, BorderLayout.CENTER);

            // Title
            titleLabel = new JLabel(p.getTitle(), SwingConstants.CENTER);
            add(titleLabel, BorderLayout.SOUTH);

            // Right-click menu
            JPopupMenu menu = new JPopupMenu();
            JMenuItem renameItem = new JMenuItem("Rename");
            JMenuItem deleteItem = new JMenuItem("Delete");

            renameItem.addActionListener(e -> renamePhoto());
            deleteItem.addActionListener(e -> deletePhoto());

            menu.add(renameItem);
            menu.add(deleteItem);
            this.setComponentPopupMenu(menu);
           
            
             this.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                selected = !selected; // toggle
                setBorder(BorderFactory.createLineBorder(selected ? Color.BLUE : Color.GRAY));
            }
        });
    }

    public boolean isSelected() {
        return selected;
    }

    public int getIndex() {
        return index;

        }

        private void renamePhoto() {
            String newName = JOptionPane.showInputDialog(this, "Enter new name:", titleLabel.getText());
            if (newName != null && !newName.trim().isEmpty()) {
                titleLabel.setText(newName.trim());
                PhotoStorage.renamePhoto(index, newName.trim());
            }
        }
        
        // Generic queue of Components


private int getPhotoIndex() {
    for (int i = 0; i < clPhotos.getComponentCount(); i++) {
        if (clPhotos.getComponent(i) == this) { // 'this' is the current card
            return i;
        }
    }
    return -1; // not found
}
  


private void deletePhoto() {
    int index = getPhotoIndex(); // find this card's index
    if (index == -1) return;

    // Remove from main panel
    Component card = clPhotos.getComponent(index);
    clPhotos.remove(card);
    clPhotos.revalidate();
    clPhotos.repaint();

    // Add to queue
    binQueue.enqueue(card);  // MyQueue handles FIFO

    // Show in bin panel
    clBin.add(card);
    clBin.revalidate();
    clBin.repaint();
}}
    



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AddItemsButton;
    private javax.swing.JButton AddToFavouritesButton;
    private javax.swing.JButton BinButton;
    private javax.swing.JLabel Collections;
    private javax.swing.JButton FavouritesButton;
    private javax.swing.JButton PhotosButton;
    private javax.swing.JButton PlusButton;
    private javax.swing.JButton ScreenshotssButton;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JPanel SearchingPanel;
    private javax.swing.JComboBox<String> SortComboBox;
    private javax.swing.JPanel WorkingPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JPanel clBin;
    private javax.swing.JPanel clFavourites;
    private javax.swing.JPanel clPhotos;
    private javax.swing.JPanel clScreenshots;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel variablePanel;
    // End of variables declaration//GEN-END:variables
}
